Repository burningmantech/ranger-clubhouse-api, pull requests merged in 2019-05, with the labels that each got.

#67 Regenerate Slack token
  .travis.yml
Labels: Task

#119 Break up pipeline so errors are caught.
  bin/deploy
Labels: Task

#120 Deploy
  bin/deploy
  bin/travis
Labels: Bug, Show Stopper

#121 Set AWS_ECR_IMAGE_NAME
  bin/deploy
Labels: Bug, Show Stopper

#122 Moar cache
  bin/.common.sh
  bin/travis
Labels: Bug, Task

#123 Cleanup deploy, fix composerw
  bin/composerw
  bin/deploy
Labels: Bug

#124 More deploy changes
  bin/deploy
  bin/travis
Labels: Task

#127 Don't use AWS_ECR_IMAGE_REPOSITORY
  bin/deploy
Labels: Bug

#37 Bulk copy credits
  app/Http/Controllers/PositionCreditController.php
  routes/api.php
Labels: Feature
